### ISSUE TITLE
suivi de la position

### ISSUE THREAD

**Issue by aslen77** [Chayma27/Projetposition#1]
En bas de votre page, offrez le service de suivi de la position, sans oublier la possibilité d'annuler le suivi.

**Comment by Chayma27** [comment]
Enfaite
Ahna Bekry Maou  Khdemna B getCcurrentPosition (show position) ! -- Heky Taatik Position Ponctuel
Par Contre Suivi De La Position L Hiya Tetekhdem B "watchposition" Ttaatik Un Suivi De Position Yany  Enty Tet'harak Oo Position Tet'harak Maak

Chek Fichier Geoloc2.html Fiha Ce Code

**Comment by aslen77** [comment]
ok thanks
